version: 2.1

orbs:
  android: circleci/android@0.2.1

dependencies:
  override:
    command:
      chmod +x gradlew

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: 
            ./gradlew build
